### PR TITLE
Add cmake build system support

### PR DESCRIPTION
**Pull request by soroshsabz**
ITNOA

Hi,

I try to add cmake build system support to this project and test it in Linux environment. I try to consistent writing CMakeLists.txt like another project in [POCO framework](https://github.com/pocoproject/poco) and I hope to little success to achieve it.

### CODE REVIEW

**Comment by soroshsabz** [comment]
@obiltschnig Hi again, did you have any plan to review this PR?

Thanks a lot.

**Comment by soroshsabz** [comment]
Hi again

Any plan to support this library?

Thanks a lot

**Comment by soroshsabz** [comment]
Hi again,

any update?

**Comment by soroshsabz** [comment]
Hi again

Any update?

**Comment by soroshsabz** [comment]
Any updates?

**Comment by soroshsabz** [comment]
@obiltschnig Any update?

**Comment by soroshsabz** [comment]
@obiltschnig Did you any plan to review it?

thanks

**Comment by aleks-f** [comment]
This library is obviously stale.

But looking at your pull, what is the reason for `diff`ing? And then even documenting that - why?

**Comment by soroshsabz** [comment]
@aleks-f I do not understand your meaning, I add `cmake` to this project, so this PR add some files to your project.

I change README.md because I add another way to building this project

thanks

**Comment by aleks-f** [comment]
> @aleks-f I do not understand your meaning, I add `cmake` to this project, so this PR add some files to your project.

I understand what this PR does. My question is: what is the reason for including `diff` files in it? If you have changed something, git can be used to display the diff of the change; why do you propose a diff file to be included in the source repository?

**Comment by soroshsabz** [comment]
@aleks-f Oh, sorry, I remove it

**Comment by soroshsabz** [comment]
@aleks-f because this project is design for build inside of original poco base code, so this `diff` file for applying on poco base code, not for this repo, as you can see in build instruction

https://github.com/soroshsabz/poco-dnssd#getting-started

**Comment by aleks-f** [comment]
That just does not sound like a feasible development plan. Think about it: I clone poco repo; how do I now clone dnssd repo into the existing poco repo?

The code should be in the `$POCO_BASE/DNSSD`, ie. `DNSSD` should be a sibling directory to `Foundation`, `Net` etc. Probably best done as a subtree of poco repo

**Comment by soroshsabz** [comment]
@aleks-f  Thanks for rapid replying

As @obiltschnig says in README.md before I create CMake for this project:

_Clone into the root of an existing POCO source tree. The POCO Foundation and Net libraries are required._

So developer must be know to where the code must be clone.

for second your sentences, I agree with you that all of this project must be in poco repo, but separation of this repo decide by @obiltschnig not by me. (I think it is good to make all of this repo as subdirectory of poco repo), so I think all of my decision is consistent with previous poco-dnssd developers decision.

thanks

**Comment by aleks-f** [comment]
adjust it for poco and send a pull request

**Comment by soroshsabz** [comment]
@aleks-f I create PR https://github.com/pocoproject/poco/pull/3933 for merging this into Poco project

please review it

thanks :)

**Comment by soroshsabz** [comment]
@aleks-f can you review this?

thanks

**Comment by soroshsabz** [comment]
Merge in main poco branch

https://github.com/pocoproject/poco/pull/4479

So close this PR

**Pull request closed without merging**
